version: '2'

services:
  app:
    image: 'aica/signpdf:1.0.0'
    build:
      context: .
    restart: always
    container_name: app
    depends_on:
      - db
    environment:
      - SIGNPDF_POSTGRES_URL=jdbc:postgresql://db:5432/pdf
      - SIGNPDF_POSTGRES_USER=postgres
      - SIGNPDF_POSTGRES_PASS=postgres
    expose:
      - 8030
    ports:
      - "8030:8030"

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=pdf
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
